---
title: "P8105_HW2_kp2809"
author: "Kimberly Lopez"
date: "2024-09-24"
output: github_document
---
```{r include=FALSE}
library(tidyverse)
```


# Problem 1 

Read and clean the data retain line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance.

```{r}

transit_df= 
  read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  na= c("NA","",".") 
  )

transit_tidy_df= 
  transit_df|>
  janitor::clean_names() 
  
select(transit_tidy_df, line:ada, -(staffing),-(staff_hours), -(exit_only) )
```
```{r}
transit_tidy_df= 
  transit_df|>
  janitor::clean_names() |>
  select( line:ada, -(staffing),-(staff_hours), -(exit_only) )

```


Convert the entry variable from character (YES vs NO) to a logical variable (the ifelse or case_match function may be useful).

```{r}
transit_tidy_df= 
  transit_df|>
  janitor::clean_names() |>
  select( line:ada, -(staffing),-(staff_hours), -(exit_only) ) |>
  mutate(
  entry = ifelse(entry =="YES", "TRUE","FALSE"))

```


