P8105_HW2_kp2809
================
Kimberly Lopez
2024-09-24

# Problem 1

Read and clean the data retain line, station, name, station latitude /
longitude, routes served, entry, vending, entrance type, and ADA
compliance.

``` r
transit_df= 
  read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  na= c("NA","",".") 
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
transit_tidy_df= 
  transit_df|>
  janitor::clean_names() 
  
select(transit_tidy_df, line:ada, -(staffing),-(staff_hours), -(exit_only) )
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <chr>, vending <chr>, ada <lgl>

``` r
transit_tidy_df= 
  transit_df|>
  janitor::clean_names() |>
  select( line:ada, -(staffing),-(staff_hours), -(exit_only) )
```

Convert the entry variable from character (YES vs NO) to a logical
variable (the ifelse or case_match function may be useful).

``` r
transit_tidy_df= 
  transit_df|>
  janitor::clean_names() |>
  select( line:ada, -(staffing),-(staff_hours), -(exit_only) ) |>
  mutate(
  entry = ifelse(entry =="YES", "TRUE","FALSE"))
```

Write a short paragraph about this dataset – explain briefly what
variables the dataset contains, describe your data cleaning steps so
far, and give the dimension (rows x columns) of the resulting dataset.
Are these data tidy?

This data set provides data on transit routes, lines, and some spatial
data. I have cleaned the names of some of these variables using the
janitor function. I have also labeled missing values. I also changed the
responses in the entry column to a logical vector of TRUE = “yes” and
FALSE = “no” entry. After selecting certain columns, there are 1858 rows
and 19 columns. This is not yet tidy data. Routes are separated into
more than one column and is not easy to follow. Aside from that, the
variable names are tidy.

How many distinct stations are there? Note that stations are identified
both by name and by line (e.g. 125th St 8th Avenue; 125st Broadway;
125st Lenox); the distinct function may be useful here.

``` r
transit_tidy_df |> 
  distinct(line, station_name)
```

    ## # A tibble: 465 × 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # ℹ 455 more rows

There are 465 distinct station names considering the two identifiers of
station name and line.

How many stations are ADA compliant?

``` r
transit_tidy_df |>
  filter(ada =="TRUE")
```

    ## # A tibble: 468 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue Atlantic Av…             40.7             -74.0 B      Q      D     
    ##  2 4 Avenue DeKalb Av                40.7             -74.0 B      Q      R     
    ##  3 4 Avenue DeKalb Av                40.7             -74.0 B      Q      R     
    ##  4 4 Avenue DeKalb Av                40.7             -74.0 B      Q      R     
    ##  5 4 Avenue DeKalb Av                40.7             -74.0 B      Q      R     
    ##  6 4 Avenue DeKalb Av                40.7             -74.0 B      Q      R     
    ##  7 4 Avenue DeKalb Av                40.7             -74.0 B      Q      R     
    ##  8 4 Avenue Pacific St               40.7             -74.0 B      Q      D     
    ##  9 4 Avenue Pacific St               40.7             -74.0 B      Q      D     
    ## 10 42nd St… Grand Centr…             40.8             -74.0 GS     4      5     
    ## # ℹ 458 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <chr>, vending <chr>, ada <lgl>

The tibble I filtered for ada compliance equal to “TRUE” returned 468
rows suggesting 468 stations are ada compliant.

What proportion of station entrances or exits without vending allow
entrance?

- station entry = true and vending = NO (entry = “YES” )
- and station exit and vending = NO

``` r
transit_df|>
  janitor::clean_names() |>
  select( line:ada, -(staffing),-(staff_hours) ) |>
  filter(entry == "YES"| exit_only == "Yes",vending== "NO") 
```

    ## # A tibble: 117 × 20
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 77th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 9th St                   40.7             -74.0 F      G      R     
    ##  4 4 Avenue Bay Ridge Av             40.6             -74.0 R      <NA>   <NA>  
    ##  5 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  6 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  7 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  8 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  9 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ## 10 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ## # ℹ 107 more rows
    ## # ℹ 13 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <chr>, exit_only <chr>, vending <chr>, ada <lgl>

- stations that allow entrance is 117.

``` r
transit_df|>
  janitor::clean_names() |>
  select( line:ada, -(staffing),-(staff_hours) ) |>
  filter(entry == "YES"| exit_only == "Yes",vending== "NO") |> 
  filter(entry=="YES")
```

    ## # A tibble: 69 × 20
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 9th St                   40.7             -74.0 F      G      R     
    ##  2 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  3 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  4 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  5 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  6 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  7 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  8 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ##  9 6 Avenue 7th Av                   40.7             -74.0 F      <NA>   <NA>  
    ## 10 6 Avenue Bergen St                40.7             -74.0 F      G      <NA>  
    ## # ℹ 59 more rows
    ## # ℹ 13 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <chr>, exit_only <chr>, vending <chr>, ada <lgl>

- after the initial condition of entry OR exits without vending,
  stations that allow entry was 69.

``` r
69/117
```

    ## [1] 0.5897436

There were 117 stations with a station entry or exit and without
vending. Of those stations, there were 69 stations that allowed entry.
Therefore, the proportion of station entrances or exits without vending
which allow entrance was 69/117 or 0.59.

Reformat data so that route number and route name are distinct
variables. - merge all route# columns

``` r
transit_tidy_route =
  transit_tidy_df |> 
  mutate(across(starts_with("route"), as.character))|>
  pivot_longer(
    cols= route1:route11, 
    names_to = "route_number", 
    names_prefix = "route",
    values_to = "route"
  )|>
  relocate(
    route_number, route,station_name
  )
```

How many distinct stations serve the A train?

Of the stations that serve the A train, how many are ADA compliant? -
ada compliant stations divided by distinct() stations that serve the ==
A train
